### ISSUE TITLE
Classic TODO items

### ISSUE THREAD

**Issue by ascott18** [ascott18/TellMeWhen#1716]
- [x] ~~Switch aura durations to LibClassicDurations~~ Not doing because LibClassicDurations still has lots of issues - class abilities randomly commented out in its data, some durations are wrong, and more. Sticking TMW's implementation for now. Added support for talents to it, just lacking diminishing returns and enemy buffs now.
- [x] Add shaman imbues to Weapon Imbue suggestion list
- [x] Off-hand imbues might not be working right? "hey, i have some buttons set up to track weapon imbue (instant poison in this case) - the main hand detection seems to work as expected, but the off hand one does not seem to be able to detect when there is a weapon imbue present. is this just busted?" (Discord)
- [x] #1715 
- [x] Check that All-Unit Buffs/Debuffs works right
- [ ] overpower and revenge procs when out of stance?
- [x] Consider switching DR data to https://www.curseforge.com/wow/addons/drlist-1-0 (and for live, too)
- [x] Combat Event icon events:
  - [x] resists
  - [x] blocks, parry, dodge
  - [ ] crushing blows
- [x] Check spellIDs of talents for Improved SW:P for aura durations : 
![image](https://user-images.githubusercontent.com/5017521/64145368-5afc8880-cdcd-11e9-922a-8674478a7837.png)
